dist: precise
language: java
jdk:
- oraclejdk7
before_install:
- chmod +x .utility/initiate-publish.sh
- > 
  if [ "$TRAVIS_REPO_SLUG" == "Mangopay/mangopay2-java-sdk" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then  
    openssl aes-256-cbc -K $encrypted_1689c6b91eac_key -iv $encrypted_1689c6b91eac_iv -in .utility/signingkey.gpg.enc -out .utility/signingkey.gpg -d;
  fi;
- cat /etc/hosts
- sudo hostname "$(hostname | cut -c1-63)"
- sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts > /tmp/hosts
- sudo mv /tmp/hosts /etc/hosts
- cat /etc/hosts
after_success:
- ".utility/initiate-publish.sh"
